version: '2'
services:
  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy:1.0.1-alpine
    container_name: datavalor-server-nginx-proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf
    network_mode: "bridge"
  acme-companion:
    restart: always
    image: nginxproxy/acme-companion:2.2.1
    container_name: datavalor-server-nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

