FROM python:3.8

RUN apt update
RUN apt install -y build-essential git

RUN ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata

WORKDIR /tmp

# Installing requirements
COPY ./requirements.txt /tmp
RUN pip install -r requirements.txt

# Installing fastg3
RUN git clone https://github.com/datavalor/fastg3.git \
    && cd fastg3 \
    && python setup.py install \
    && cd .. \
    && rm -rf fastg3

EXPOSE 8050