# Constants definition
G12_COLUMN_NAME = "_violating_tuple"
G3_COLUMN_NAME = "_g3_to_remove"
SELECTION_COLUMN_NAME = "_selected"
ADESIT_COLUMNS = [G12_COLUMN_NAME, G3_COLUMN_NAME, SELECTION_COLUMN_NAME]

ADESIT_INDEX = "id"

PROJ_AXES = ['__PROJ1', '__PROJ2']

TABLE_MAX_ROWS = 16

SELECTED_COLOR_BAD = "#EFF22C"
SELECTED_COLOR_GOOD = "#008000"
CE_COLOR = "#EF553B"
FREE_COLOR = "#636EFA"

NON_ANALYSED_COLOR = "#000000"

GRAPHS_BACKGROUND = '#E5ECF6'