# ADESIT COLUMNS IN DATASET
ADESIT_INDEX = "id"
G12_COLUMN_NAME = "_violating_tuple"
G3_COLUMN_NAME = "_g3_to_remove"
SELECTION_COLUMN_NAME = "_selected"
PROJ_AXES = ['__PROJ1', '__PROJ2']

# MAX NUMBER OF ROWS IN DATATABLES
TABLE_MAX_ROWS = 16

# COLOR PALETTE
NON_ANALYSED_COLOR = "#000000"
SELECTED_COLOR_BAD = "#EFF22C"
SELECTED_COLOR_GOOD = "#008000"
CE_COLOR = "#EF553B"
FREE_COLOR = "#636EFA"
GRAPHS_BACKGROUND = '#E5ECF6'

# LIMITS WHEN RUNNING ON WEB
RESOURCE_LIMITED = False
MAX_N_TUPLES = 100000
MAX_N_ATTRS = 20
VPE_TIMEOUT = 10